### ISSUE TITLE
probleme de reboot gladys lors de lancement du script

### ISSUE THREAD

**Issue by tof38** [GladysProject/gladys-speak#3]
sur la version 3.7.3
après installation du module, google voice n'apparaît pas dans la liste de choix des notifications.
Le lancement du script exemple fait rebooter gladys.

**Comment by Pierre-Gilles** [comment]
Hello, pour tous les problèmes de supports le mieux est de poser les questions sur la communauté Gladys :) 

https://community.gladysproject.com/
